#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'manage.py syncdb --noinput'"
python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput

python manage.py createsuperuser --noinput --username=admin --email richard-oss@esplins.org
# manage.py changepassword won't accept password on the commandline
admin_pass=`cat ${OPENSHIFT_DATA_DIR}/CREDENTIALS`
echo "from django.contrib.auth.models import User; u=User.objects.get(username__exact='admin'); u.set_password('${admin_pass}'); u.save()" |
python manage.py shell

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/foodcheck/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/foodcheck/manage.py collectstatic --noinput
